---
- name: Deploy Nginx container
  hosts: servers
  become: true

  tasks:
    - name: Run Nginx container
      community.docker.docker_container:
        name: "{{ web_app_name }}"
        image: "{{ web_app_image }}"
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "{{ web_app_host_port }}:{{ web_app_container_port }}"

